# Generated by Django 4.2.4 on 2024-05-11 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GoodsModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="商品名称")),
                ("image", models.ImageField(upload_to="goods/", verbose_name="商品图片")),
                ("description", models.TextField(verbose_name="商品描述")),
                (
                    "create_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="添加时间"),
                ),
                ("update_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
            ],
            options={
                "verbose_name": "商品",
                "verbose_name_plural": "商品",
                "db_table": "goods",
            },
        ),
        migrations.CreateModel(
            name="PriceModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField()),
                ("status", models.BooleanField(default=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="goods.goodsmodel",
                    ),
                ),
            ],
            options={
                "verbose_name": "价格",
                "verbose_name_plural": "价格",
                "db_table": "price",
            },
        ),
    ]
