# Generated by Django 5.0.6 on 2024-05-27 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("goods", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CategoryModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="类别名")),
            ],
            options={
                "verbose_name": "类别",
                "verbose_name_plural": "类别",
                "db_table": "category",
            },
        ),
        migrations.CreateModel(
            name="PriceCycleModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="周期名字")),
                ("start_date", models.DateField(verbose_name="周期开始时间")),
                ("end_date", models.DateField(verbose_name="周期结束时间")),
                ("status", models.BooleanField(default=True, verbose_name="周期状态")),
                ("creater_id", models.BigIntegerField(verbose_name="创建人ID")),
                (
                    "create_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="添加时间"),
                ),
                ("update_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
            ],
            options={
                "verbose_name": "价格周期",
                "verbose_name_plural": "价格周期",
                "db_table": "price_cycle",
            },
        ),
        migrations.CreateModel(
            name="UnitModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=10, verbose_name="单位名称")),
            ],
            options={
                "verbose_name": "单位",
                "verbose_name_plural": "单位",
                "db_table": "unit",
            },
        ),
        migrations.CreateModel(
            name="GoodsModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="商品名称")),
                ("image", models.ImageField(upload_to="goods/", verbose_name="商品图片")),
                (
                    "ori_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="商品初始价格",
                    ),
                ),
                ("description", models.TextField(verbose_name="商品描述")),
                ("status", models.BooleanField(default=True, verbose_name="商品状态")),
                (
                    "create_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="添加时间"),
                ),
                ("update_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="goods.categorymodel",
                        verbose_name="商品类别",
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="goods.unitmodel",
                    ),
                ),
            ],
            options={
                "verbose_name": "商品",
                "verbose_name_plural": "商品",
                "db_table": "goods",
            },
        ),
        migrations.CreateModel(
            name="PriceModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="当前报价"
                    ),
                ),
                ("start_date", models.DateField(verbose_name="价格开始时间")),
                ("end_date", models.DateField(verbose_name="价格结束时间")),
                (
                    "status",
                    models.CharField(
                        choices=[(0, "未申报"), (1, "未审核"), (2, "已审核")],
                        default=0,
                        max_length=10,
                        verbose_name="报价状态",
                    ),
                ),
                (
                    "creater_id",
                    models.BigIntegerField(
                        blank=True, default=None, null=True, verbose_name="报价人ID"
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(
                        blank=True, default=None, null=True, verbose_name="报价申报时间"
                    ),
                ),
                (
                    "reviewer_id",
                    models.BigIntegerField(
                        blank=True, default=None, null=True, verbose_name="审核人ID"
                    ),
                ),
                (
                    "review_time",
                    models.DateTimeField(
                        blank=True, default=None, null=True, verbose_name="报价审核时间"
                    ),
                ),
                (
                    "cycle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prices",
                        to="goods.pricecyclemodel",
                        verbose_name="关联周期",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prices",
                        to="goods.goodsmodel",
                        verbose_name="关联商品",
                    ),
                ),
            ],
            options={
                "verbose_name": "价格",
                "verbose_name_plural": "价格",
                "db_table": "price",
            },
        ),
        migrations.CreateModel(
            name="PriceRequestModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("requested_at", models.DateTimeField(auto_now_add=True)),
                (
                    "price",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="goods.pricemodel",
                    ),
                ),
                (
                    "product",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="goods.goodsmodel",
                    ),
                ),
            ],
            options={
                "verbose_name": "价格请求",
                "verbose_name_plural": "价格请求",
                "db_table": "price_request",
            },
        ),
    ]
