# Generated by Django 4.2.4 on 2024-05-12 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("goods", "0002_alter_pricemodel_product"),
    ]

    operations = [
        migrations.CreateModel(
            name="UnitModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=10, verbose_name="单位名称")),
            ],
            options={
                "verbose_name": "单位",
                "verbose_name_plural": "单位",
                "db_table": "unit",
            },
        ),
        migrations.AddField(
            model_name="pricemodel",
            name="unit",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="goods.unitmodel",
            ),
        ),
    ]
