# Generated by Django 5.0.6 on 2024-05-30 11:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("goods", "0003_alter_pricemodel_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pricemodel",
            name="status",
            field=models.CharField(
                choices=[(0, "未申报"), (1, "未审核"), (2, "已审核"), (-1, "已拒绝"), (4, "过期")],
                default=0,
                max_length=10,
                verbose_name="报价状态",
            ),
        ),
    ]
