# Generated by Django 5.0.6 on 2024-05-20 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("goods", "0003_unitmodel_pricemodel_unit"),
    ]

    operations = [
        migrations.CreateModel(
            name="CategoryModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="类别名")),
            ],
            options={
                "verbose_name": "类别",
                "verbose_name_plural": "类别",
                "db_table": "category",
            },
        ),
        migrations.AddField(
            model_name="goodsmodel",
            name="category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="goods.categorymodel",
                verbose_name="商品类别",
            ),
        ),
    ]
