# Generated by Django 5.0.6 on 2024-06-04 16:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("goods", "0004_alter_pricemodel_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="goodsmodel",
            name="ori_price",
        ),
        migrations.AlterField(
            model_name="goodsmodel",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="goods/", verbose_name="商品图片"
            ),
        ),
        migrations.AlterField(
            model_name="goodsmodel",
            name="status",
            field=models.BooleanField(default=False, verbose_name="商品状态"),
        ),
    ]
