# Generated by Django 5.0.6 on 2024-05-20 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("goods", "0004_categorymodel_goodsmodel_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="goodsmodel",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="goods.categorymodel",
                verbose_name="商品类别",
            ),
        ),
    ]
