# Generated by Django 5.0.6 on 2024-06-04 17:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("goods", "0005_remove_goodsmodel_ori_price_alter_goodsmodel_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="goodsmodel",
            name="status",
            field=models.BooleanField(default=True, verbose_name="商品状态"),
        ),
    ]
