# Generated by Django 5.0.6 on 2024-05-24 16:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("goods", "0005_alter_goodsmodel_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pricemodel",
            name="status",
            field=models.BooleanField(default=False),
        ),
    ]
