# Generated by Django 5.0.6 on 2024-05-24 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("goods", "0006_alter_pricemodel_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="PriceRequestModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("requested_at", models.DateTimeField(auto_now_add=True)),
                (
                    "price",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="request",
                        to="goods.pricemodel",
                    ),
                ),
            ],
            options={
                "verbose_name": "价格请求",
                "verbose_name_plural": "价格请求",
                "db_table": "price_request",
            },
        ),
    ]
