# Generated by Django 4.2.4 on 2024-06-04 22:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("goods", "0006_alter_goodsmodel_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="goodsmodel",
            name="ori_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="商品初始价格",
            ),
        ),
        migrations.AlterField(
            model_name="pricemodel",
            name="status",
            field=models.CharField(
                choices=[(0, "未申报"), (1, "未审核"), (2, "已审核"), (-1, "已拒绝"), (-99, "已弃用")],
                default=0,
                max_length=10,
                verbose_name="报价状态",
            ),
        ),
    ]
