# Generated by Django 5.0.6 on 2024-06-06 11:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("goods", "0007_goodsmodel_ori_price_alter_pricemodel_status"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PriceRequestModel",
        ),
    ]
