# Generated by Django 5.0.6 on 2024-05-24 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("goods", "0007_pricerequestmodel"),
    ]

    operations = [
        migrations.AddField(
            model_name="pricerequestmodel",
            name="product",
            field=models.OneToOneField(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pricerequest",
                to="goods.goodsmodel",
            ),
            preserve_default=False,
        ),
    ]
