# Generated by Django 5.0.6 on 2024-05-24 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("goods", "0008_pricerequestmodel_product"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pricemodel",
            name="unit",
        ),
        migrations.AddField(
            model_name="goodsmodel",
            name="unit",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="goods.unitmodel",
            ),
            preserve_default=False,
        ),
    ]
