# Generated by Django 5.0.6 on 2024-05-24 18:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("goods", "0009_remove_pricemodel_unit_goodsmodel_unit"),
    ]

    operations = [
        migrations.AddField(
            model_name="goodsmodel",
            name="status",
            field=models.BooleanField(default=True, verbose_name="商品状态"),
        ),
    ]
