# Generated by Django 5.0.6 on 2024-06-27 16:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("goods", "0009_alter_pricemodel_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="goodsmodel",
            name="unit",
        ),
        migrations.AlterField(
            model_name="goodsmodel",
            name="description",
            field=models.TextField(verbose_name="商品规格"),
        ),
        migrations.DeleteModel(
            name="UnitModel",
        ),
    ]
