# Generated by Django 5.0.6 on 2024-06-28 18:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("goods", "0010_remove_goodsmodel_unit_alter_goodsmodel_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="goodsmodel",
            name="ori_price_check_1",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="商品初始询价1",
            ),
        ),
        migrations.AddField(
            model_name="goodsmodel",
            name="ori_price_check_2",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="商品初始询价2",
            ),
        ),
        migrations.AddField(
            model_name="goodsmodel",
            name="ori_price_check_avg",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="商品初始评价询价",
            ),
        ),
        migrations.AddField(
            model_name="pricemodel",
            name="price_check_1",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="询价1",
            ),
        ),
        migrations.AddField(
            model_name="pricemodel",
            name="price_check_2",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="询价2",
            ),
        ),
        migrations.AddField(
            model_name="pricemodel",
            name="price_check_avg",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="平均询价",
            ),
        ),
        migrations.AlterField(
            model_name="goodsmodel",
            name="ori_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="商品初始价格(下调5%)",
            ),
        ),
    ]
