# Generated by Django 5.0.6 on 2024-07-01 19:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("goods", "0011_goodsmodel_ori_price_check_1_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="goodsmodel",
            options={"verbose_name": "商品"},
        ),
        migrations.AlterField(
            model_name="goodsmodel",
            name="description",
            field=models.CharField(max_length=100, verbose_name="商品规格"),
        ),
    ]
