# Generated by Django 5.0.6 on 2024-07-01 19:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("goods", "0012_alter_goodsmodel_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="goodsmodel",
            options={"verbose_name": "商品", "verbose_name_plural": "商品"},
        ),
        migrations.AlterUniqueTogether(
            name="goodsmodel",
            unique_together={("name", "description")},
        ),
    ]
