# Generated by Django 5.0.6 on 2024-07-01 19:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("goods", "0013_alter_goodsmodel_options_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="goodsmodel",
            unique_together=set(),
        ),
    ]
