# Generated by Django 5.0.6 on 2024-07-08 19:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("goods", "0014_alter_goodsmodel_unique_together"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="goodsmodel",
            name="ori_price",
        ),
        migrations.RemoveField(
            model_name="goodsmodel",
            name="ori_price_check_1",
        ),
        migrations.RemoveField(
            model_name="goodsmodel",
            name="ori_price_check_2",
        ),
        migrations.RemoveField(
            model_name="goodsmodel",
            name="ori_price_check_avg",
        ),
    ]
