# Generated by Django 5.0.6 on 2024-08-20 10:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("goods", "0015_remove_goodsmodel_ori_price_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="goodsmodel",
            name="brand",
            field=models.CharField(default=0, max_length=100, verbose_name="商品品牌"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="goodsmodel",
            name="license",
            field=models.ImageField(
                blank=True, null=True, upload_to="license/", verbose_name="商品资质"
            ),
        ),
        migrations.AlterField(
            model_name="pricemodel",
            name="status",
            field=models.CharField(
                choices=[
                    ("0", "未申报"),
                    ("1", "未审核"),
                    ("2", "已审核"),
                    ("-1", "已拒绝"),
                    ("-99", "已弃用"),
                ],
                db_index=True,
                default=0,
                max_length=10,
                verbose_name="报价状态",
            ),
        ),
    ]
