# Generated by Django 4.2.4 on 2024-08-23 13:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("goods", "0016_goodsmodel_brand_goodsmodel_license_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="goodsmodel",
            name="brand",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="商品品牌"
            ),
        ),
    ]
