# Generated by Django 4.2.4 on 2024-08-24 16:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("goods", "0017_alter_goodsmodel_brand"),
    ]

    operations = [
        migrations.AlterField(
            model_name="goodsmodel",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="goods/%Y/%m/%d", verbose_name="商品图片"
            ),
        ),
        migrations.AlterField(
            model_name="goodsmodel",
            name="license",
            field=models.ImageField(
                blank=True, null=True, upload_to="license/%Y/%m/%d", verbose_name="商品资质"
            ),
        ),
    ]
