# Generated by Django 4.2.4 on 2024-08-27 16:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("goods", "0018_alter_goodsmodel_image_alter_goodsmodel_license"),
    ]

    operations = [
        migrations.AlterField(
            model_name="goodsmodel",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="goods/", verbose_name="商品图片"
            ),
        ),
        migrations.AlterField(
            model_name="goodsmodel",
            name="license",
            field=models.ImageField(
                blank=True, null=True, upload_to="license/", verbose_name="商品资质"
            ),
        ),
    ]
