# Generated by Django 5.1 on 2024-09-02 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0019_alter_goodsmodel_image_alter_goodsmodel_license'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodsmodel',
            name='license',
            field=models.FileField(blank=True, null=True, upload_to='license/', verbose_name='商品资质'),
        ),
    ]
