# Generated by Django 5.0.6 on 2024-06-13 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0002_alter_cartmodel_quantity_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="orderdetailmodel",
            old_name="product_des",
            new_name="description",
        ),
        migrations.AlterField(
            model_name="cartmodel",
            name="funds",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="orders.fundsmodel",
                verbose_name="经费实例",
            ),
        ),
    ]
