# Generated by Django 4.2.4 on 2024-06-14 11:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0003_rename_product_des_orderdetailmodel_description_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ordersmodel",
            name="finish_status",
        ),
    ]
