# Generated by Django 4.2.4 on 2024-06-16 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0004_remove_ordersmodel_finish_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderdetailmodel",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="details",
                to="orders.ordersmodel",
                verbose_name="订单实例",
            ),
        ),
    ]
