# Generated by Django 5.0.6 on 2024-06-17 14:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0005_alter_orderdetailmodel_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="ordersmodel",
            name="finish_num",
            field=models.IntegerField(default=0, verbose_name="完成项个数"),
        ),
        migrations.AddField(
            model_name="ordersmodel",
            name="product_num",
            field=models.IntegerField(default=0, verbose_name="订单项个数"),
        ),
    ]
