# Generated by Django 5.0.6 on 2024-08-20 10:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0007_remove_orderdetailmodel_unit_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cartmodel",
            name="creater_id",
            field=models.IntegerField(db_index=True, verbose_name="加购人ID"),
        ),
        migrations.AlterField(
            model_name="orderdetailmodel",
            name="category",
            field=models.CharField(max_length=100, verbose_name="商品类别"),
        ),
        migrations.AlterField(
            model_name="ordersmodel",
            name="creater_id",
            field=models.IntegerField(db_index=True, verbose_name="订单创建人ID"),
        ),
        migrations.AlterField(
            model_name="ordersmodel",
            name="status",
            field=models.CharField(
                choices=[
                    ("0", "待接单"),
                    ("1", "待发货"),
                    ("2", "配送中"),
                    ("3", "配送完成"),
                    ("4", "已收货待复核"),
                    ("5", "订单有疑问"),
                    ("6", "订单完成"),
                    ("-1", "撤销"),
                ],
                db_index=True,
                max_length=10,
                verbose_name="订单状态",
            ),
        ),
    ]
