# Generated by Django 5.0.6 on 2024-08-20 17:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0008_alter_cartmodel_creater_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ordersmodel",
            name="deliver_date",
            field=models.DateField(blank=True, null=True, verbose_name="订单预定送达日期"),
        ),
    ]
