# Generated by Django 5.0.6 on 2024-08-22 13:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0009_ordersmodel_deliver_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderdetailmodel",
            name="brand",
            field=models.CharField(default="", max_length=100, verbose_name="商品品牌"),
            preserve_default=False,
        ),
    ]
