# Generated by Django 4.2.4 on 2024-08-24 15:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0010_orderdetailmodel_brand"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderdetailmodel",
            name="brand",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="商品品牌"
            ),
        ),
    ]
