# Generated by Django 4.2.4 on 2024-08-26 22:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0011_alter_orderdetailmodel_brand"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderdetailmodel",
            name="image",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="商品图片"
            ),
        ),
        migrations.AddField(
            model_name="orderdetailmodel",
            name="license",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="商品许可证"
            ),
        ),
    ]
