# Generated by Django 4.2.4 on 2024-08-29 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("goods", "0019_alter_goodsmodel_image_alter_goodsmodel_license"),
        ("orders", "0012_orderdetailmodel_image_orderdetailmodel_license"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orderdetailmodel",
            name="image",
        ),
        migrations.RemoveField(
            model_name="orderdetailmodel",
            name="license",
        ),
        migrations.AddField(
            model_name="ordersmodel",
            name="cycle",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="goods.pricecyclemodel",
                verbose_name="价格周期",
            ),
        ),
    ]
