# Generated by Django 4.2.4 on 2024-09-04 21:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0015_ordersmodel_note"),
    ]

    operations = [
        migrations.AddField(
            model_name="cartmodel",
            name="note",
            field=models.TextField(blank=True, null=True, verbose_name="备注"),
        ),
        migrations.AddField(
            model_name="orderdetailmodel",
            name="note",
            field=models.TextField(blank=True, null=True, verbose_name="备注"),
        ),
    ]
