# Generated by Django 4.2.4 on 2024-09-15 11:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0016_cartmodel_note_orderdetailmodel_note"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderLogModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("operator_id", models.IntegerField(verbose_name="操作人ID")),
                (
                    "operate_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="操作时间"),
                ),
                ("operation", models.TextField(verbose_name="操作内容")),
            ],
            options={
                "verbose_name": "订单日志",
                "verbose_name_plural": "订单日志",
                "db_table": "order_log",
            },
        ),
    ]
